# node version: 21-alpine
FROM node:21-alpine

COPY ./ ./

RUN npm install

# Run the app

# npm run startUS => Users Service
CMD ["npm", "run", "start"]
# # npm run startCS => Comments Service
# CMD ["npm", "run", "startCS"]